MF_TO_ID_DICT = {

    # Equity
    "Aditya Birla Sun Life Equity Advantage Fund - Direct Plan": 15697,
    "Aditya Birla Sun Life Equity Fund": 561,
    "Aditya Birla Sun Life Equity Fund - Direct Plan": 15741,
    "Aditya Birla Sun Life Focused Equity Fund": 2865,
    "Aditya Birla Sun Life Focused Equity Fund - Direct Plan": 15883,
    "Aditya Birla Sun Life Frontline Equity Fund": 1400,
    "Aditya Birla Sun Life Frontline Equity Fund - Direct Plan": 15831,
    "Aditya Birla Sun Life Small Cap Fund": 5006,
    "Aditya Birla Sun Life Small Cap Fund - Direct Plan": 15935,
    "Aditya Birla Sun Life Tax Relief 96": 24,
    "Aditya Birla Sun Life Tax Relief 96 - Direct Plan": 15889,
    "Axis Bluechip Fund": 10780,
    "Axis Bluechip Fund - Direct Plan": 15682,
    "Axis Focused 25 Fund": 14951,
    "Axis Focused 25 Fund - Direct Plan": 15684,
    "Axis Long Term Equity Fund": 10826,
    "Axis Long Term Equity Fund - Direct Plan": 15688,
    "Axis Midcap Fund": 12052,
    "Axis Midcap Fund - Direct Plan": 15690,
    "Axis Small Cap Fund - Direct Plan": 22335,
    "Axis Small Cap Fund - Regular Plan": 22333,
    "Baroda Banking and Financial Services Fund": 14946,
    "Baroda Banking and Financial Services Fund - Direct Plan": 15698,
    "Baroda Midcap Fund": 11534,
    "Baroda Midcap Fund - Direct Plan": 15783,
    "BNP Paribas Large Cap Fund": 2338,
    "BNP Paribas Large Cap Fund - Direct Plan": 15719,
    "BNP Paribas Long Term Equity Fund": 3001,
    "BNP Paribas Long Term Equity Fund - Direct Plan": 15732,
    "BNP Paribas Multi Cap Fund": 2830,
    "BNP Paribas Multi Cap Fund - Direct Plan": 15716,
    "BOI AXA Manufacturing & Infrastructure Fund": 10854,
    "BOI AXA Manufacturing & Infrastructure Fund - Direct Plan": 15735,
    "BOI AXA Tax Advantage Fund - Direct Plan": 16803,
    "BOI AXA Tax Advantage Fund - Regular Plan": 10097,
    "Canara Robeco Bluechip Equity Fund - Direct Plan": 15765,
    "Canara Robeco Bluechip Equity Fund - Regular Plan": 11333,
    "Canara Robeco Emerging Equities Fund - Direct Plan": 16581,
    "Canara Robeco Emerging Equities Fund - Regular Plan": 2645,
    "Canara Robeco Equity Diversified Fund - Direct Plan": 16588,
    "Canara Robeco Equity Diversified Fund - Regular Plan": 1839,
    "Canara Robeco Equity Tax Saver Fund - Direct Plan": 16594,
    "Canara Robeco Equity Tax Saver Fund - Regular Plan": 59,
    "Canara Robeco Infrastructure Fund - Regular Plan": 2960,
    "DSP Equity Fund": 393,
    "DSP Equity Fund - Direct Plan": 16386,
    "DSP Equity Opportunities Fund": 776,
    "DSP Equity Opportunities Fund - Direct Plan": 16425,
    "DSP Focus Fund": 11183,
    "DSP Focus Fund - Direct Plan": 16388,
    "DSP Midcap Fund - Direct Plan": 16438,
    "DSP Midcap Fund - Regular Plan": 3725,
    "DSP Small Cap Fund - Direct Plan": 16411,
    "DSP Small Cap Fund - Regular Plan": 5069,
    "DSP T.I.G.E.R. Fund - Direct Plan": 16410,
    "DSP T.I.G.E.R. Fund - Regular Plan": 2222,
    "DSP Tax Saver Fund": 3985,
    "DSP Tax Saver Fund - Direct Plan": 16454,
    "Edelweiss Large & Mid Cap Fund - Direct Plan": 16569,
    "Edelweiss Large & Mid Cap Fund Regular Plan": 4871,
    "Edelweiss Large Cap Fund - Direct Plan": 17352,
    "Edelweiss Large Cap Fund - Regular Plan": 10432,
    "Edelweiss Long Term Equity Fund": 17762,
    "Edelweiss Long Term Equity Fund": 10125,
    "Edelweiss Mid Cap Fund - Direct Plan": 16586,
    "Edelweiss Mid Cap Fund - Regular Plan": 6227,
    "Edelweiss Multi Cap Fund - Direct Plan": 29263,
    "Edelweiss Multi Cap Fund - Regular Plan": 29261,
    "Essel Large Cap Equity Fund": 13264,
    "Essel Large Cap Equity Fund - Direct Plan": 16461,
    "Essel Long Term Advantage Fund": 31263,
    "Essel Long Term Advantage Fund - Direct Plan": 31265,
    "Franklin Build India Fund": 10563,
    "Franklin Build India Fund - Direct Plan": 15979,
    "Franklin India Equity Fund": 116,
    "Franklin India Equity Fund - Direct Plan": 16008,
    "Franklin India Focused Equity Fund": 5141,
    "Franklin India Focused Equity Fund - Direct Plan": 15990,
    "Franklin India Index Fund - NSE Nifty Plan": 834,
    "Franklin India Prima Fund": 115,
    "Franklin India Prima Fund - Direct Plan": 16003,
    "Franklin India Smaller Companies Fund": 3019,
    "Franklin India Smaller Companies Fund - Direct Plan": 16010,
    "Franklin India Taxshield Fund": 601,
    "Franklin India Taxshield Fund - Direct Plan": 16014,
    "HDFC Capital Builder Value Fund": 218,
    "HDFC Capital Builder Value Fund - Direct Plan": 15989,
    "HDFC Equity Fund": 219,
    "HDFC Equity Fund - Direct Plan": 16026,
    "HDFC Index Fund - Sensex Plan": 1370,
    "HDFC Index Fund - Sensex Plan - Direct Plan": 16071,
    "HDFC Index Fund Nifty 50 Plan": 1368,
    "HDFC Index Fund Nifty 50 Plan - Direct Plan": 16069,
    "HDFC Mid-Cap Opportunities Fund": 5067,
    "HDFC Mid-Cap Opportunities Fund - Direct Plan": 16114,
    "HDFC Retirement Savings Fund Equity Plan - Direct Plan": 31780,
    "HDFC Retirement Savings Fund Equity Plan - Regular Plan": 31779,
    "HDFC Small Cap Fund - Direct Plan": 16617,
    "HDFC Small Cap Fund - Regular Plan": 6770,
    "HDFC Top 100 Fund": 104,
    "HDFC Top 100 Fund - Direct Plan": 16164,
    "HSBC Large Cap Equity Fund": 1481,
    "HSBC Large Cap Equity Fund - Direct Plan": 16289,
    "ICICI Prudential Banking and Financial Services Fund": 8293,
    "ICICI Prudential Banking and Financial Services Fund - Direct Plan": 15936,
    "ICICI Prudential Bluechip Fund": 7517,
    "ICICI Prudential Bluechip Fund - Direct Plan": 15841,
    "ICICI Prudential Infrastructure Fund - Direct Plan": 15849,
    "ICICI Prudential Large & Mid Cap Fund": 534,
    "ICICI Prudential Large & Mid Cap Fund - Direct Plan": 15868,
    "ICICI Prudential Long Term Equity Fund": 640,
    "ICICI Prudential Long Term Equity Fund": 15862,
    "ICICI Prudential Midcap Fund": 2439,
    "ICICI Prudential Midcap Fund - Direct Plan": 15960,
    "ICICI Prudential Multicap Fund": 86,
    "ICICI Prudential Multicap Fund - Direct Plan": 15874,
    "ICICI Prudential Nifty Index Fund": 1236,
    "ICICI Prudential Nifty Index Fund - Direct Plan": 15959,
    "ICICI Prudential Nifty Next 50 Index Fund": 11236,
    "ICICI Prudential Smallcap Fund": 5646,
    "ICICI Prudential Value Discovery Fund": 2310,
    "ICICI Prudential Value Discovery Fund - Direct Plan": 15822,
    "IDBI Diversified Equity Fund - Direct Plan": 25144,
    "IDBI Equity Advantage Fund - Direct Plan": 20683,
    "IDBI Equity Advantage Fund - Regular Plan": 20681,
    "IDFC Core Equity Fund - Direct Plan": 16474,
    "IDFC Core Equity Fund - Regular Plan": 2797,
    "IDFC Focused Equity Fund - Direct Plan": 16507,
    "IDFC Infrastructure Fund - Direct Plan": 16514,
    "IDFC Infrastructure Fund - Regular Plan": 12129,
    "IDFC Nifty Fund - Direct Plan": 16504,
    "IDFC Nifty Fund - Regular Plan": 11154,
    "IDFC Sterling Value Fund - Direct Plan": 16498,
    "IDFC Sterling Value Fund - Regular Plan": 6693,
    "IDFC Tax Advantage": 16493,
    "IDFC Tax Advantage": 10032,
    "IIFL Focused Equity Fund - Direct Plan": 28458,
    "IIFL Focused Equity Fund - Regular Plan": 28456,
    "Indiabulls Bluechip Fund": 14013,
    "Indiabulls Bluechip Fund - Direct Plan": 15579,
    "Invesco India Contra Fund": 4278,
    "Invesco India Contra Fund - Direct Plan": 16719,
    "Invesco India Financial Services Fund": 7830,
    "Invesco India Financial Services Fund - Direct Plan": 16702,
    "Invesco India Growth Opportunities Fund": 5346,
    "Invesco India Growth Opportunities Fund - Direct Plan": 16770,
    "Invesco India Infrastructure Fund": 5882,
    "Invesco India Infrastructure Fund - Direct Plan": 16774,
    "Invesco India Largecap Fund": 10565,
    "Invesco India Largecap Fund - Direct Plan": 16712,
    "Invesco India Mid Cap Fund": 4280,
    "Invesco India Mid Cap Fund - Direct Plan": 16807,
    "Invesco India Tax Plan": 3913,
    "Invesco India Tax Plan - Direct Plan": 16849,
    "JM Core 11 Fund": 6673,
    "JM Core 11 Fund - Direct Plan": 16539,
    "JM Multicap Fund": 8653,
    "JM Multicap Fund - Direct Plan": 16547,
    "JM Tax Gain Fund": 6679,
    "JM Tax Gain Fund - Direct Plan": 16552,
    "Kotak Bluechip Fund - Direct Plan": 16337,
    "Kotak Bluechip Fund - Regular Plan": 577,
    "Kotak Emerging Equity Fund - Direct Plan": 17134,
    "Kotak Emerging Equity Fund Regular Plan": 4270,
    "Kotak Equity Opportunities Fund - Direct Plan": 16378,
    "Kotak Equity Opportunities Fund - Regular Plan": 2360,
    "Kotak India EQ Contra Fund - Direct Plan": 16341,
    "Kotak India EQ Contra Fund - Regular Plan": 2780,
    "Kotak Infrastructure and Economic Reform Fund -Std Standard Plan": 6669,
    "Kotak Infrastructure and Economic Reform Fund -Std Standard Plan - Direct Plan": 16508,
    "Kotak Small Cap Fund - Direct Plan": 16382,
    "Kotak Small Cap Fund - Regular Plan": 2597,
    "Kotak Tax Saver - Direct Plan": 16380,
    "Kotak Tax Saver Regular Plan": 2937,
    "KotakStd Standard Multicap Fund - Direct Plan": 17140,
    "KotakStd Standard Multicap Fund Regular Plan": 10594,
    "L&T Emerging Businesses Fund": 26131,
    "L&T Emerging Businesses Fund - Direct Plan": 26133,
    "L&T Equity Fund": 2686,
    "L&T India Value Fund": 10789,
    "L&T India Value Fund - Direct Plan": 16269,
    "L&T Infrastructure Fund": 5564,
    "L&T Infrastructure Fund - Direct Plan": 16275,
    "L&T Large and Midcap Fund": 3326,
    "L&T Large and Midcap Fund - Direct Plan": 16266,
    "L&T Midcap Fund": 2333,
    "L&T Midcap Fund - Direct Plan": 16280,
    "L&T Tax Advantage Fund": 3112,
    "L&T Tax Advantage Fund - Direct Plan": 16200,
    "LIC MF Index-Sensex Plan": 1479,
    "LIC MF Index-Sensex Plan - Direct Plan": 16798,
    "LIC MF Large & Mid Cap Fund - Direct Plan": 29416,
    "LIC MF Large & Mid Cap Fund - Regular Plan": 29414,
    "LIC MF Large Cap Fund - Direct Plan": 16781,
    "LIC MF Tax Plan": 405,
    "LIC MF Tax Plan - Direct Plan": 16868,
    "Mirae Asset Emerging Bluechip Fund - Direct Plan": 16563,
    "Mirae Asset Emerging Bluechip Fund - Regular Plan": 11213,
    "Mirae Asset Large Cap Fund - Direct Plan": 16575,
    "Mirae Asset Large Cap Fund - Regular Plan": 6762,
    "Mirae Asset Tax Saver Fund - Direct Plan": 31318,
    "Mirae Asset Tax Saver Fund - Regular Plan": 31316,
    "Motilal Oswal Focused 25 Fund - Direct Plan": 19514,
    "Motilal Oswal Focused 25 Fund - Regular Plan": 19512,
    "Motilal Oswal Long Term Equity Fund - Direct Plan": 29162,
    "Motilal Oswal Long Term Equity Fund - Regular Plan": 29160,
    "Motilal Oswal Midcap 30 Fund - Direct Plan": 24080,
    "Motilal Oswal Multicap 35 Fund - Direct Plan": 26125,
    "Motilal Oswal Multicap 35 Fund - Regular Plan": 26123,
    "Nippon India Banking Fund": 1708,
    "Nippon India Banking Fund - Direct Plan": 16048,
    "Nippon India Focused Equity Fund": 3900,
    "Nippon India Focused Equity Fund - Direct Plan": 16129,
    "Nippon India Growth Fund": 183,
    "Nippon India Growth Fund - Direct Plan": 16083,
    "Nippon India Index Fund - Nifty Plan": 11536,
    "Nippon India Index Fund - Nifty Plan - Direct Plan": 16856,
    "Nippon India Index Fund - Sensex Plan": 11541,
    "Nippon India Index Fund - Sensex Plan - Direct Plan": 16859,
    "Nippon India Large Cap Fund": 5270,
    "Nippon India Large Cap Fund - Direct Plan": 16192,
    "Nippon India Multi Cap Fund": 2640,
    "Nippon India Retirement Fund - Wealth Creation Scheme": 29289,
    "Nippon India Retirement Fund - Wealth Creation Scheme - Direct Plan": 29291,
    "Nippon India Small Cap Fund": 11463,
    "Nippon India Small Cap Fund - Direct Plan": 16182,
    "Nippon India Value Fund": 2790,
    "Nippon India Value Fund - Direct Plan": 16175,
    "Parag Parikh Long Term Equity Fund - Direct Plan": 19701,
    "Parag Parikh Long Term Equity Fund - Regular Plan": 19699,
    "PGIM India Diversified Equity Fund - Direct Plan": 29473,
    "PGIM India Large Cap Fund - Direct Plan": 15574,
    "PGIM India Long Term Equity Fund - Direct Plan": 31167,
    "PGIM India Long Term Equity Fund - Regular Plan": 31165,
    "Principal Emerging Bluechip Fund": 9429,
    "Principal Emerging Bluechip Fund - Direct Plan": 16573,
    "Principal Focused Multicap Fund": 2916,
    "Principal Focused Multicap Fund - Direct Plan": 16614,
    "Principal Multi Cap Growth Fund": 866,
    "Principal Multi Cap Growth Fund - Direct Plan": 16580,
    "Principal Tax Savings Fund": 89,
    "Principal Tax Savings Fund - Direct Plan": 16650,
    "Quant Active Fund": 952,
    "Quant Active Fund - Direct Plan": 17361,
    "Quant Tax Plan": 818,
    "Quant Tax Plan - Direct Plan": 17381,
    "Quantum Equity FoF - Regular Plan #": 33962,
    "Quantum Equity FoF Fund - Direct Plan": 10550,
    "Quantum Long Term Equity Value Fund - Direct Plan": 3181,
    "Quantum Long Term Equity Value Fund - Regular Plan #": 33968,
    "Quantum Tax Saving - Regular Plan #": 33972,
    "SBI Banking & Financial Services Fund - Direct Plan": 29463,
    "SBI Banking & Financial Services Fund - Regular Plan": 29461,
    "SBI Bluechip Fund": 3083,
    "SBI Bluechip Fund - Direct Plan": 16198,
    "SBI Focused Equity Fund": 2415,
    "SBI Focused Equity Fund - Direct Plan": 16324,
    "SBI Infrastructure Fund": 5071,
    "SBI Infrastructure Fund - Direct Plan": 17161,
    "SBI Large & Midcap Fund": 197,
    "SBI Large & Midcap Fund - Direct Plan": 16240,
    "SBI Magnum Multicap Fund": 2859,
    "SBI Magnum Multicap Fund - Direct Plan": 17514,
    "SBI Nifty Index Fund": 1164,
    "SBI Nifty Index Fund - Direct Plan": 16233,
    "SBI Small Cap Fund": 10603,
    "SBI Small Cap Fund - Direct Plan": 15787,
    "Sundaram Diversified Equity Fund": 687,
    "Sundaram Financial Services Opportunities Fund - Regular Plan": 7611,
    "Sundaram Infrastructure Advantage Fund - Direct Plan": 16138,
    "Sundaram Infrastructure Advantage Fund - Regular Plan": 2832,
    "Sundaram Large and Mid Cap Fund": 4152,
    "Sundaram Large and Mid Cap Fund - Direct Plan": 16086,
    "Sundaram Select Focus Fund - Direct Plan": 16120,
    "Sundaram Select Focus Fund - Regular Plan": 1384,
    "Tata Banking and Financial Services Fund - Direct Plan": 31356,
    "Tata Banking and Financial Services Fund - Regular Plan": 31354,
    "Tata Equity PE Fund - Direct Plan": 16952,
    "Tata Equity PE Fund - Regular Plan": 2267,
    "Tata Index Nifty Fund - Direct Plan": 16954,
    "Tata Index Nifty Fund - Regular Plan": 1550,
    "Tata Index Sensex Fund - Direct Plan": 16955,
    "Tata Index Sensex Fund - Regular Plan": 1551,
    "Tata India Tax Savings Fund": 212,
    "Tata India Tax Savings Fund - Direct Plan": 16739,
    "Tata Infrastructure Fund - Direct Plan": 16703,
    "Tata Infrastructure Fund - Regular Plan": 2543,
    "Tata Large & Mid Cap Fund - Direct Plan": 16679,
    "Tata Large & Mid Cap Fund - Regular Plan": 102,
    "Tata Large Cap Fund - Direct Plan": 16729,
    "Tata Midcap Growth Fund - Direct Plan": 16717,
    "Tata Midcap Growth Fund - Regular Plan": 103,
    "Tata Retirement Savings Fund - Progressive Plan - Direct Plan": 17020,
    "Tata Retirement Savings Fund - Progressive Plan - Regular Plan": 13413,
    "Taurus Banking & Financial Services Fund - Direct Plan": 17023,
    "Taurus Banking & Financial Services Fund - Regular Plan": 14718,
    "Taurus Discovery": 16656,
    "Taurus Discovery": 215,
    "Taurus Tax Shield Fund - Direct Plan": 16713,
    "Taurus Tax Shield Fund - Regular Plan": 83,
    "UTI Children's Career Fund-Investment Plan - Direct Plan": 15867,
    "UTI Children's Career Fund-Investment Plan - Regular Plan": 2090,
    "UTI Equity Fund - Direct Plan": 15714,
    "UTI Equity Fund - Regular Plan": 247,
    "UTI Infrastructure Fund - Regular Plan": 2140,
    "UTI Mastershare Fund - Direct Plan": 15789,
    "UTI Mastershare Fund - Regular Plan": 22,
    "UTI Nifty Index Fund - Direct Plan": 15830,
    "UTI Nifty Index Fund - Regular Plan": 757,

    # Hybrid
    "Aditya Birla Sun Life Arbitrage Fund": 10586,
    "Aditya Birla Sun Life Arbitrage Fund - Direct Plan": 15739,
    "Aditya Birla Sun Life Asset Allocator Multi-Manager FoF Scheme": 3514,
    "Aditya Birla Sun Life Asset Allocator Multi-Manager FoF Scheme - Direct Plan": 16889,
    "Aditya Birla Sun Life Balanced Advantage Fund": 797,
    "Aditya Birla Sun Life Balanced Advantage Fund - Direct Plan": 16897,
    "Aditya Birla Sun Life Equity Hybrid '95 Fund": 511,
    "Aditya Birla Sun Life Equity Hybrid '95 Fund - Direct Plan": 15692,
    "Aditya Birla Sun Life Regular Savings Fund": 2234,
    "Aditya Birla Sun Life Regular Savings Fund - Direct Plan": 15919,
    "Axis Arbitrage Fund - Direct Plan": 27587,
    "Axis Equity Saver Fund - Direct Plan": 30703,
    "Axis Equity Saver Fund - Regular Plan": 30700,
    "Baroda Conservative Hybrid Fund": 2407,
    "Baroda Conservative Hybrid Fund - Direct Plan": 15779,
    "BNP Paribas Conservative Hybrid Fund": 2345,
    "BNP Paribas Conservative Hybrid Fund - Direct Plan": 15728,
    "Canara Robeco Conservative Hybrid Fund - Direct Plan": 15770,
    "Canara Robeco Conservative Hybrid Fund - Regular Plan": 976,
    "Canara Robeco Equity Hybrid Fund - Direct Plan": 16384,
    "Canara Robeco Equity Hybrid Fund - Regular Plan": 75,
    "DSP Dynamic Asset Allocation Fund - Direct Plan": 23438,
    "DSP Dynamic Asset Allocation Fund - Regular Plan": 23436,
    "DSP Equity & Bond Fund": 610,
    "DSP Equity & Bond Fund - Direct Plan": 15793,
    "DSP Equity Savings Fund - Direct Plan": 32141,
    "Edelweiss Arbitrage Fund - Direct Plan": 27145,
    "Edelweiss Arbitrage Fund - Regular Plan": 27142,
    "Edelweiss Balanced Advantage Fund - Direct Plan": 17768,
    "Edelweiss Balanced Advantage Fund - Regular Plan": 10607,
    "Edelweiss Equity Savings Fund - Direct Plan": 28229,
    "Edelweiss Equity Savings Fund - Regular Plan": 28226,
    "Essel Regular Savings Fund - Direct Plan": 16466,
    "Franklin India Debt Hybrid Fund": 860,
    "Franklin India Dynamic Asset Allocation Fund of Funds": 1915,
    "Franklin India Dynamic Asset Allocation Fund of Funds - Direct Plan": 16024,
    "Franklin India Equity Hybrid Fund": 692,
    "Franklin India Equity Hybrid Fund - Direct Plan": 16020,
    "Franklin India Life Stage Fund of Funds 40s": 1982,
    "Franklin India Life Stage Fund of Funds 40s - Direct Plan": 16036,
    "Franklin India Life Stage Fund of Funds 50s Plus": 1984,
    "Franklin India Life Stage Fund of Funds 50s Plus - Direct Plan": 16040,
    "Franklin India Life Stage Fund of Funds 50s Plus - Floating Rate": 2304,
    "Franklin India Life Stage Fund of Funds 50s Plus - Floating Rate - Direct Plan": 16044,
    "HDFC Children's Gift Fund": 936,
    "HDFC Children's Gift Fund - Direct Plan": 15995,
    "HDFC Equity Savings Fund": 2374,
    "HDFC Equity Savings Fund - Direct Plan": 16118,
    "HDFC Hybrid Debt Fund": 1930,
    "HDFC Hybrid Equity Fund": 2668,
    "HDFC Hybrid Equity Fund - Direct Plan": 16132,
    "HDFC Retirement Savings Fund - Hybrid Debt Plan - Direct Plan": 31784,
    "HDFC Retirement Savings Fund - Hybrid Debt Plan - Regular Plan": 31783,
    "HDFC Retirement Savings Fund - Hybrid Equity Plan - Direct Plan": 31782,
    "HDFC Retirement Savings Fund - Hybrid Equity Plan - Regular Plan": 31781,
    "HSBC Managed Solutions India - Conservative - Regular Plan": 25866,
    "HSBC Managed Solutions India - Growth - Regular Plan": 25858,
    "ICICI Prudential Balanced Advantage Fund": 3906,
    "ICICI Prudential Balanced Advantage Fund - Direct Plan": 15829,
    "ICICI Prudential Child Care Fund - Gift Plan": 1031,
    "ICICI Prudential Child Care Fund - Gift Plan - Direct Plan": 15940,
    "ICICI Prudential Equity & Debt Fund": 686,
    "ICICI Prudential Equity & Debt Fund - Direct Plan": 15815,
    "ICICI Prudential Equity Arbitrage Fund": 3902,
    "ICICI Prudential Equity Arbitrage Fund - Direct Plan": 17396,
    "ICICI Prudential Equity Savings Fund": 28743,
    "ICICI Prudential Equity Savings Fund - Direct Plan": 28822,
    "ICICI Prudential Moderate Fund": 1933,
    "ICICI Prudential Moderate Fund - Direct Plan": 17836,
    "ICICI Prudential Regular Savings Fund": 2100,
    "ICICI Prudential Regular Savings Fund - Direct Plan": 15851,
    "IDFC Arbitrage Fund - Direct Plan": 17551,
    "IDFC Arbitrage Fund - Regular Plan": 3971,
    "IDFC Asset Allocation Fund - Conservative Plan - Direct Plan": 17859,
    "IDFC Asset Allocation Fund - Conservative Plan - Regular Plan": 10844,
    "IDFC Asset Allocation Fund - Moderate Plan - Direct Plan": 17861,
    "IDFC Asset Allocation Fund - Moderate Plan - Regular Plan": 10848,
    "IDFC Dynamic Equity Fund - Direct Plan": 28342,
    "IDFC Dynamic Equity Fund - Regular Plan": 28340,
    "IDFC Regular Savings Fund - Direct Plan": 16525,
    "IDFC Regular Savings Fund - Regular Plan": 10841,
    "Indiabulls Arbitrage Fund - Direct Plan": 28950,
    "Indiabulls Arbitrage Fund - Regular Plan": 28947,
    "Indiabulls Savings Income Fund - Direct Plan": 31269,
    "Indiabulls Savings Income Fund - Regular Plan": 31267,
    "Invesco India Arbitrage Fund - Direct Plan": 16368,
    "Invesco India Dynamic Equity Fund": 5566,
    "Invesco India Dynamic Equity Fund - Direct Plan": 16740,
    "Kotak Asset Allocator Fund - Direct Plan": 17436,
    "Kotak Asset Allocator Fund Regular Plan": 2308,
    "Kotak Debt Hybrid Fund - Direct Plan": 17795,
    "Kotak Debt Hybrid Fund - Regular Plan": 1901,
    "Kotak Equity Arbitrage Fund - Direct Plan": 17136,
    "Kotak Equity Arbitrage Fund Regular Plan": 2882,
    "Kotak Equity Hybrid Fund - Direct Plan": 16338,
    "Kotak Equity Hybrid Fund - Regular Plan": 707,
    "Kotak Equity Savings Fund - Direct Plan": 28168,
    "Kotak Equity Savings Fund - Regular Plan": 28165,
    "L&T Arbitrage Opportunities Fund - Direct Plan": 27300,
    "L&T Arbitrage Opportunities Fund - Regular Plan": 27296,
    "L&T Balanced Advantage Fund - Direct Plan": 16259,
    "L&T Conservative Hybrid Fund": 1814,
    "L&T Conservative Hybrid Fund - Direct Plan": 16290,
    "L&T Hybrid Equity Fund": 12056,
    "L&T Hybrid Equity Fund - Direct Plan": 16264,
    "Mirae Asset Hybrid Equity Fund - Direct Plan": 30604,
    "Mirae Asset Hybrid Equity Fund - Regular Plan": 30602,
    "Motilal Oswal Dynamic Fund - Direct Plan": 32933,
    "Motilal Oswal Dynamic Fund - Regular Plan": 32930,
    "Nippon India Arbitrage Fund": 11625,
    "Nippon India Arbitrage Fund - Direct Plan": 17008,
    "Nippon India Equity Hybrid Fund": 2791,
    "Nippon India Equity Hybrid Fund - Direct Plan": 16159,
    "Nippon India Hybrid Bond Fund": 1990,
    "Nippon India Hybrid Bond Fund - Direct Plan": 16144,
    "PGIM India Arbitrage Fund - Regular Plan": 27870,
    "PGIM India Equity Savings Fund": 2059,
    "PGIM India Equity Savings Fund - Direct Plan": 16392,
    "Principal Equity Savings Fund": 1306,
    "Principal Equity Savings Fund - Direct Plan": 16819,
    "Principal Hybrid Equity Fund": 714,
    "Principal Hybrid Equity Fund - Direct Plan": 16521,
    "SBI Debt Hybrid Fund": 960,
    "SBI Debt Hybrid Fund - Direct Plan": 17516,
    "SBI Dynamic Asset Allocation Fund - Direct Plan": 29720,
    "SBI Dynamic Asset Allocation Fund - Regular Plan": 29718,
    "SBI Equity Hybrid Fund": 204,
    "SBI Equity Hybrid Fund - Direct Plan": 16215,
    "SBI Equity Savings Fund - Direct Plan": 30277,
    "SBI Equity Savings Fund - Regular Plan": 30274,
    "SBI Magnum Children's Benefit Fund": 1229,
    "SBI Magnum Children's Benefit Fund - Direct Plan": 17524,
    "Sundaram Equity Hybrid Fund - Direct Plan": 16079,
    "Sundaram Equity Hybrid Fund - Regular Plan": 813,
    "Tata Equity Savings Fund - Direct Plan": 17502,
    "Tata Equity Savings Fund - Regular Plan": 837,
    "Tata Hybrid Equity Fund - Direct Plan": 16662,
    "Tata Retirement Savings Fund - Conservative Plan - Direct Plan": 17019,
    "Tata Retirement Savings Fund - Conservative Plan - Regular Plan": 13415,
    "Tata Retirement Savings Fund - Moderate Plan - Direct Plan": 17017,
    "Tata Retirement Savings Fund - Moderate Plan - Regular Plan": 13414,
    "UTI Arbitrage Fund - Direct Plan": 17771,
    "UTI Arbitrage Fund - Regular Plan": 3464,
    "UTI Regular Savings Fund - Direct Plan": 15804,
    "UTI Regular Savings Fund - Regular Plan": 1993
}