MF_TO_ID_DICT = {

    # Large Cap
    "Aditya Birla Sun Life Focused Equity Fund - Direct Plan  (Erstwhile Aditya Birla Sun Life Top 100)": 15883,
    "Axis Bluechip Fund  (Erstwhile Axis Equity)": 10780,
    "Axis Bluechip Fund - Direct Plan(Erstwhile Axis Equity)": 15682,
    "Canara Robeco Bluechip Equity Fund - Direct Plan(Erstwhile Canara Robeco Large Cap+ Regular)": 15765,
    "Edelweiss Large Cap Fund - Direct Plan  (Erstwhile Edelweiss Large Cap Advantage Fund)": 17352,
    "HDFC Index Fund - Sensex Plan": 1370,
    "HDFC Index Fund - Sensex Plan - Direct Plan": 16071,
    "HDFC Top 100 Fund  (Erstwhile HDFC Top 200)": 104,
    "HDFC Top 100 Fund - Direct Plan (Erstwhile HDFC Top 200)": 16164,
    "ICICI Prudential Bluechip Fund  (Erstwhile ICICI Prudential Focused Bluechip Equity)": 7517,
    "ICICI Prudential Bluechip Fund - Direct Plan(Erstwhile ICICI Prudential Focused Bluechip Equity)": 15841,
    "Indiabulls Bluechip Fund - Direct Plan": 15579,
    "Invesco India Largecap Fund - Direct Plan  (Erstwhile Invesco India Business Leaders)": 16712,
    "JM Core 11 Fund": 6673,
    "JM Core 11 Fund - Direct Plan": 16539,
    "Kotak Bluechip Fund - Direct Plan  (Erstwhile Kotak 50)": 16337,
    "Mirae Asset Large Cap Fund - Direct Plan(Erstwhile Mirae Asset India Equity Fund)": 16575,
    "Motilal Oswal Focused 25 Fund - Direct Plan (Erstwhile Motilal Oswal MOSt Focused 25)": 19514,
    "Reliance Large Cap Fund (Erstwhile Reliance Top 200)": 5270,
    "Reliance Large Cap Fund - Direct Plan  (Erstwhile Reliance Top 200)": 16192,
    "SBI Bluechip Fund": 3083,
    "SBI Bluechip Fund - Direct Plan": 16198,
    "Sundaram Select Focus Fund - Direct Plan": 16120,
    "UTI Nifty Index Fund - Direct Plan": 15830,


    # Large & MidCap
    "Canara Robeco Emerging Equities Fund - Direct Plan": 16581,
    "Invesco India Growth Opportunities Fund (Erstwhile Invesco India Growth)": 5346,
    "Invesco India Growth Opportunities Fund - Direct Plan  (Erstwhile Invesco India Growth)": 16770,
    "Kotak Equity Opportunities Fund - Direct Plan  (Erstwhile Kotak Opportunities)": 16378,
    "LIC MF Large & Mid Cap Fund - Direct Plan  (Erstwhile LIC MF Midcap Fund)": 29416,
    "Mirae Asset Emerging Bluechip Fund - Direct Plan": 16563,
    "Principal Emerging Bluechip Fund": 9429,
    "Principal Emerging Bluechip Fund - Direct Plan": 16573,
    "Sundaram Large and Mid Cap Fund (Erstwhile Sundaram Equity Multiplier)": 4152,
    "Sundaram Large and Mid Cap Fund - Direct Plan  (Erstwhile Sundaram Equity Multiplier)": 16086,


    # Multi cap
    "Aditya Birla Sun Life Equity Fund": 561,
    "Aditya Birla Sun Life Equity Fund - Direct Plan": 15741,
    "Axis Focused 25 Fund": 14951,
    "Axis Focused 25 Fund - Direct Plan": 15684,
    "Canara Robeco Equity Diversified Fund - Direct Plan": 16588,
    "Edelweiss Multi Cap Fund - Direct Plan  (Erstwhile Edelweiss Economic Resurgence Fund)": 29263,
    "Franklin India Focused Equity Fund  (Erstwhile Franklin India High Growth Companies)": 5141,
    "Franklin India Focused Equity Fund - Direct Plan(Erstwhile Franklin India High Growth Companies)": 15990,
    "HDFC Retirement Savings Fund Equity Plan - Direct Plan": 31780,
    "ICICI Prudential Multicap Fund": 86,
    "ICICI Prudential Multicap Fund - Direct Plan": 15874,
    "IIFL Focused Equity Fund - Direct Plan  (Erstwhile IIFL India Growth Fund)": 28458,
    "JM Multicap Fund - Direct Plan  (Erstwhile JM Multi Strategy)": 16547,
    "Kotak Standard Multicap Fund - Direct Plan  (Erstwhile Kotak Select Focus)": 17140,
    "Motilal Oswal Multicap 35 Fund - Direct Plan(Erstwhile Motilal Oswal MOSt Focused Multicap 35 Fund)": 26125,
    "Parag Parikh Long Term Equity Fund - Direct Plan(Erstwhile Parag Parikh Long Term Value Fund)": 19701,
    "Quant Active Fund  (Erstwhile Quant Growth Fund)": 952,
    "SBI Focused Equity Fund (Erstwhile SBI Emerging Businesses)": 2415,
    "SBI Focused Equity Fund - Direct Plan  (Erstwhile SBI Emerging Businesses)": 16324,
    "SBI Magnum Multicap Fund": 2859,
    "SBI Magnum Multicap Fund - Direct Plan": 17514,
    "Tata Retirement Savings Fund - Progressive Plan - Direct Plan": 17020,

    # Mid cap
    "Axis Midcap Fund": 12052,
    "Axis Midcap Fund - Direct Plan": 15690,
    "DSP Midcap Fund - Direct Plan": 16438,
    "Franklin India Prima Fund": 115,
    "Franklin India Prima Fund - Direct Plan": 16003,
    "HDFC Mid-Cap Opportunities Fund": 5067,
    "Invesco India Mid Cap Fund - Direct Plan": 16807,
    "Kotak Emerging Equity Scheme - Direct Plan": 17134,
    "L&T Midcap Fund": 2333,
    "L&T Midcap Fund - Direct Plan": 16280,

    # Small Cap
    "Axis Small Cap Fund - Direct Plan": 22335,
    "HDFC Small Cap Fund - Direct Plan": 16617,
    "L&T Emerging Businesses Fund": 26131,
    "L&T Emerging Businesses Fund - Direct Plan": 26133,
    "Reliance Small Cap Fund": 11463,
    "Reliance Small Cap Fund - Direct Plan": 16182,
    "SBI Small Cap Fund  (Erstwhile SBI Small & Midcap)": 10603,
    "SBI Small Cap Fund - Direct Plan(Erstwhile SBI Small & Midcap)": 15787,
    "Franklin India Smaller Companies Fund - Direct Plan ": 16010,

    # Value Oriented/ Contra Funds
    "Invesco India Contra Fund": 4278,
    "Invesco India Contra Fund - Direct Plan": 16719,
    "Kotak India EQ Contra Fund - Direct Plan(Erstwhile Kotak Classic Equity)": 16341,
    "L&T India Value Fund": 10789,
    "L&T India Value Fund - Direct Plan": 16269,
    "Tata Equity PE Fund - Direct Plan": 16952,

    # ELSS
    "Aditya Birla Sun Life Tax Relief 96": 24,
    "Aditya Birla Sun Life Tax Relief 96 - Direct Plan": 15889,
    "Axis Long Term Equity Fund": 10826,
    "Axis Long Term Equity Fund - Direct Plan": 15688,
    "Canara Robeco Equity Tax Saver Fund - Direct Plan": 16594,
    "DSP Tax Saver Fund": 3985,
    "DSP Tax Saver Fund - Direct Plan": 16454,
    "IDFC Tax Advantage (ELSS) Fund - Direct Plan": 16493,
    "Invesco India Tax Plan": 3913,
    "Invesco India Tax Plan - Direct Plan": 16849,
    "JM Tax Gain Fund": 6679,
    "JM Tax Gain Fund - Direct Plan": 16552,
    "Kotak Tax Saver - Direct Plan": 16380,
    "Mirae Asset Tax Saver Fund - Direct Plan": 31318,
    "Motilal Oswal Long Term Equity Fund - Direct Plan  (Erstwhile Motilal Oswal MOSt Focused Long Term Fund)": 29162,
    "Quant Tax Plan": 818,
    "Quant Tax Plan - Direct Plan": 17381,
    "Tata India Tax Savings Fund": 212,
    "Tata India Tax Savings Fund - Direct Plan": 16739,

    # hybrid

    "Principal Hybrid Equity Fund - Direct Plan": 16521,


}